---
- name: configure os
  set_fact:
    server_base_os: "{{ansible_distribution|lower}}{{ansible_distribution_major_version|int}}"

- name: include os variables
  include_vars: "{{server_base_os}}.yml"

# define os variables

- name: define docker_swagger_editor_apache2_restart_command
  set_fact:
    docker_swagger_editor_apache2_restart_command: "{{__docker_swagger_editor_apache2_restart_command}}"
  when: docker_swagger_editor_apache2_restart_command is not defined

# docker container

- name: install container
  docker_container:
    name: "{{docker_swagger_editor_container_name}}"
    image: "swaggerapi/swagger-editor:{{docker_swagger_editor_version}}"
    state: "{{docker_swagger_editor_state}}"
    ports:
      - "{{docker_swagger_editor_container_port}}:8080"

# setup os

- name: setup {{server_base_os}}
  include: "{{server_base_os}}.yml"